// bars-30d.js
// Replaces Upptime's response-time sparkline with a 30-day granular bar per service.
// Uses Upptime CSS variables to blend with the original theme.

(async () => {
  // Identify the default branch dynamically to fetch summary.json reliably.
  // We infer it from the <meta property="og:url"> or fall back to 'master'/'main'.
  const repoPathMatch = (document.querySelector('link[rel="canonical"]')?.href || location.href)
    .match(/https:\/\/([^/]+)\.github\.io\/([^/]+)\//i);
  // Fallbacks if we can't parse owner/repo from URL:
  const OWNER = (repoPathMatch && 'Randomness8546') || 'Randomness8546';
  const REPO  = (repoPathMatch && 'upptime-8546513546545641235478') || 'upptime-8546513546545641235478';

  // Try both 'main' then 'master' for summary.json
  async function fetchSummary() {
    const urls = [
      `https://raw.githubusercontent.com/${OWNER}/${REPO}/main/history/summary.json`,
      `https://raw.githubusercontent.com/${OWNER}/${REPO}/master/history/summary.json`,
    ];
    for (const u of urls) {
      const r = await fetch(u, { cache: 'no-store' });
      if (r.ok) return r.json();
    }
    throw new Error('Unable to fetch history/summary.json from main or master.');
  }

  // Helper: build last 30 days ISO list
  const DAYS = 30;
  const today = new Date(); today.setHours(0,0,0,0);
  const toISO = d => d.toISOString().slice(0,10);
  const days = [...Array(DAYS)].map((_, i) => {
    const d = new Date(today); d.setDate(d.getDate() - (DAYS - 1 - i));
    return toISO(d);
  });

  // Thresholds for granular coloring (tweak if you wish)
  const L1 = 5, L2 = 60, L3 = 180;
  const level = (m) => (m <= 0 ? 'lvl0' : m <= L1 ? 'lvl1' : m <= L2 ? 'lvl2' : 'lvl3');

  // Inject minimal CSS that uses Upptime theme vars
  const css = `
  .u-bars { display:grid; grid-auto-flow:column; grid-auto-columns: 10px; gap:3px; margin-top:4px; }
  .u-bars .cell { width:10px; height:18px; border-radius:2px; border: 1px solid transparent; }
  .u-bars .lvl0 { background: color-mix(in oklab, var(--ok, #16a34a) 22%, transparent); border-color: color-mix(in oklab, var(--ok, #16a34a) 40%, transparent); }
  .u-bars .lvl1 { background: color-mix(in oklab, var(--warn, #f59e0b) 30%, transparent); border-color: color-mix(in oklab, var(--warn, #f59e0b) 50%, transparent); }
  .u-bars .lvl2 { background: color-mix(in oklab, #f97316 40%, transparent); border-color: color-mix(in oklab, #f97316 60%, transparent); }
  .u-bars .lvl3 { background: color-mix(in oklab, var(--down, #ef4444) 45%, transparent); border-color: color-mix(in oklab, var(--down, #ef4444) 65%, transparent); }
  /* Hide default response-time images/sparklines to avoid duplication */
  table.status-table td:nth-child(4) img { display:none !important; }
  `;
  const style = document.createElement('style');
  style.textContent = css;
  document.head.appendChild(style);

  // Load Upptime summary with dailyMinutesDown
  // (This file is generated by Upptime’s summary job and used by badges/graphs.) [2](https://hashes.com/en/tools/hash_identifier)
  const summary = await fetchSummary();

  // Build a quick lookup: slug -> data
  const map = new Map(summary.map(s => [String(s.slug || '').toLowerCase(), s]));

  // Find the main services table (Upptime renders a status table on the homepage)
  const table = document.querySelector('table.status-table');
  if (!table) return;

  // Determine column indexes by header text (more robust than nth-child)
  const headers = Array.from(table.querySelectorAll('thead th')).map(th => th.textContent.trim().toLowerCase());
  const historyIdx = headers.findIndex(h => h.includes('history'));
  const respIdx    = headers.findIndex(h => h.includes('response'));

  if (historyIdx === -1 || respIdx === -1) return;

  // Iterate rows, find slug from "History" column link (e.g., google.yml), then draw bars into the Response Time cell
  Array.from(table.querySelectorAll('tbody tr')).forEach(tr => {
    const histCell = tr.children[historyIdx];
    const respCell = tr.children[respIdx];
    const a = histCell?.querySelector('a[href$=".yml"]');
    if (!a) return;

    const slug = a.getAttribute('href').replace(/\.yml$/i,'').toLowerCase();
    const svc = map.get(slug);
    if (!svc) return;

    // Build the bar
    const strip = document.createElement('div');
    strip.className = 'u-bars';
    days.forEach(day => {
      const m = (svc.dailyMinutesDown && svc.dailyMinutesDown[day]) || 0;
      const cell = document.createElement('div');
      cell.className = `cell ${level(m)}`;
      cell.title = `${svc.name || slug}\n${day} — ${m > 0 ? m + ' min down' : '0 min (up)'}`;
      strip.appendChild(cell);
    });

    // Insert underneath the response‑time summary text (keep ms label, replace sparkline image)
    // We already hide images in CSS; just append our bars for visual context
    respCell.appendChild(strip);
  });
})();
