# Change these first
owner: Randomness8546 # Your GitHub organization or username, where this repository lives
repo: upptime-8546513546545641235478 # The name of this repository

sites:
  - name: Google
    url: https://www.google.be
  - name: Live Odoo - Web
    url: $LiveOdooWeb
  - name: Live Odoo - Websocket
    url: $LiveOdooWebsocket
  - name: Live Odoo - Database
    url: $LIVEODOODATABASE
  - name: Acc Odoo - Web
    url: https://acc-odoo.bontexgeo.com/web/health
  - name: Acc Odoo - Websocket
    url: https://acc-odoo.bontexgeo.com/websocket/health
  - name: Acc Odoo - Database
    url: https://acc-odoo.bontexgeo.com/web/health?db_server_status=1
  - name: Sandbox Odoo - Web
    url: https://sandbox-odoo.bontexgeo.com/web/health
  - name: Sandbox Odoo - Websocket
    url: https://sandbox-odoo.bontexgeo.com/websocket/health
  - name: Sandbox Odoo - Database
    url: https://sandbox-odoo.bontexgeo.com/web/health?db_server_status=1
  - name: BTG
    url: vpn.bontexgeo.com
    type: globalping
    check: icmp-ping
    location: europe
  - name: ABG
    url: vpn.abgltd.com
    type: globalping
    check: icmp-ping
    location: europe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-8546513546545641235478
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
